[workspace]
members = ["common", "console", "ts-client", "ts-client/tests", "tests/rust"]

default-members = ["console", "ts-client"]
resolver = "2"

[workspace.package]
version = "1.0.0"
edition = "2021"
description = "A library for interacting with Casper CEPs for the Casper network."
readme = "README.md"
homepage = "https://github.com/gRoussac/ceps-rust-ts-client.git"
repository = "https://github.com/gRoussac/ceps-rust-ts-client.git"
authors = ["3099551+gRoussac@users.noreply.github.com"]
license-file = "LICENSE"


[workspace.dependencies]
casper-rust-wasm-sdk = { version = "2.0.0", git = "https://github.com/casper-ecosystem/rustSDK", branch = "dev" }

[profile.release]
codegen-units = 1
lto = true

[patch.crates-io]
casper-types = { version = "5.0.0", git = "https://github.com/casper-network/casper-node", branch = "dev" }
casper-client = { version = "3.0.1", git = "https://github.com/casper-ecosystem/casper-client-rs", branch = "feat-track-node-2.0" }
casper-binary-port = { version = "1.0.0", git = "https://github.com/casper-network/casper-node", branch = "dev" }
casper-binary-port-access = { version = "0.1.0", git = "https://github.com/gRoussac/casper-binary-port-client", branch = "binary_response_changes" }
