[package]
name = "integration-tests"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
publish = false

[lib]
name = "integration_tests"
bench = false
doctest = false

[dependencies]
ceps-client = { path = "../../ceps-client" }
casper-rust-wasm-sdk.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }
serde_json.workspace = true
