[package]
name = "ts-client"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]
name = "ts_client"
path = "src/lib.rs"

[dependencies]
casper-rust-wasm-sdk.workspace = true
wasm-bindgen = "*"
js-sys = "*"
gloo-utils = { version = "0.2", default-features = false, features = ["serde"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
ts-client-tests = { path = "tests" }
